[build-system]
requires = ["hatchling>=1.5"]
build-backend = "hatchling.build"

[project]
name = "jupyter-events"
description = "Jupyter Event System library"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name = "Jupyter Development Team", email = "jupyter@googlegroups.com" },
]
keywords = [
    "Jupyter",
    "JupyterLab",
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "jsonschema[format-nongpl,format_nongpl]>=4.3.0",
    "python-json-logger",
    "pyyaml",
    "traitlets",
]
dynamic = [
    "version",
]

[project.license]
file = 'COPYING.md'

[project.urls]
Homepage = "http://jupyter.org"

[project.scripts]
jupyter-events = "jupyter_events.cli:main"

[project.optional-dependencies]
test = [
    "coverage",
    "pre-commit",
    "pytest-asyncio>=0.19.0",
    "pytest-console-scripts",
    "pytest-cov",
    "pytest>=6.1.0",
    # [cli]
    "click",
    "rich",
]
cli = [
    "click",
    "rich"
]

[tool.hatch.version]
path = "jupyter_events/_version.py"

[tool.jupyter-releaser]
skip = ["check-links"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-raXs --durations 10 --color=yes --doctest-modules"
testpaths = [
    "tests/"
]
asyncio_mode = "auto"
script_launch_mode = "subprocess"
