version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "dev-requirements.txt" }}-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "dev-requirements.txt" }}-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            # Have CircleCI display pretty test result output
            mkdir test-reports
            py.test --cov=jupyter_telemetry --junitxml=test-reports/junit.xml tests/
            # Upload coverage info to codecov
            codecov

      - run:
          name: run linter
          command: |
            python -m flake8 jupyter_telemetry --max-line-length 120

      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports